[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "targets/i686-unknown-none.json"

[target.i686-unknown-none]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]